imap:
  host: "" # leave empty to use the environment variable EM_SMTP_HOST
  port: 993
  username: "" # leave empty to use the environment variable EM_SMTP_USERNAME
  password: "" # leave empty to use the environment variable EM_SMTP_PASSWORD
interval: 25 # in minutes
printing:
  min_copies: 2 # number of duplicate copies to be printed
  printer: null # "HP_LaserJet_400_M401dn" # printer name // TODO: add instructions on how to get the printer name
  amt: 1 # AMT number (Funkkenner, ohne führende 0)
